// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetColorArgs {
    pub color: String,
}

impl From<SetColorArgs> for super::Reducer {
    fn from(args: SetColorArgs) -> Self {
        Self::SetColor { color: args.color }
    }
}

impl __sdk::InModule for SetColorArgs {
    type Module = super::RemoteModule;
}

pub struct SetColorCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_color`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_color {
    /// Request that the remote module invoke the reducer `set_color` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_color`] callbacks.
    fn set_color(&self, color: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_color`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetColorCallbackId`] can be passed to [`Self::remove_on_set_color`]
    /// to cancel the callback.
    fn on_set_color(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SetColorCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_color`],
    /// causing it not to run in the future.
    fn remove_on_set_color(&self, callback: SetColorCallbackId);
}

impl set_color for super::RemoteReducers {
    fn set_color(&self, color: String) -> __sdk::Result<()> {
        self.imp.call_reducer("set_color", SetColorArgs { color })
    }
    fn on_set_color(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SetColorCallbackId {
        SetColorCallbackId(self.imp.on_reducer(
            "set_color",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetColor { color },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, color)
            }),
        ))
    }
    fn remove_on_set_color(&self, callback: SetColorCallbackId) {
        self.imp.remove_on_reducer("set_color", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_color`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_color {
    /// Set the call-reducer flags for the reducer `set_color` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_color(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_color for super::SetReducerFlags {
    fn set_color(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_color", flags);
    }
}
